In [21]:
import pandas as pd

In [22]:
df_normalized_before_processing = pd.read_csv('normalized_vaccine_data_processed.csv')
df_not_normalized_before_processing = pd.read_csv('not_normalized_vaccine_data_processed.csv')

In [23]:
A = ["S.VaccineImportantHealth",
     "S.VaccineEffectiveSevere",
     "S.VaccineImportantPublic",
     "S.VaccineBeneficialMOH",
     "S.VaccineSafe",
     "S.MOHInfoTrusted",
     "S.VaccineProtectInfection",
     "S.AgreeMOHRecommendation",
     "S.WorriedSideEffects",
     "S.PreventNewVariant"]

B = ["P.ProtectFlu",
     "P.ProtectSevereComp",
     "P.EffectivenessVsRisk",
     "P.ClinicallyTested",
     "P.LongTermSideEffects",
     "P.TrustReportsMOH",
     "P.ChipBelief",
     "P.MandatoryBelief",
     "P.HalalDoubt",
     "P.AlternativeMedicineBelief",
     "P.HighRiskJob",
     "P.WorkDemand"]

C = ["A.BoosterProtectSevere",
     "A.BoosterProtectFamily",
     "A.BoosterPreventSpread",
     "A.ReturnDailyActivities",
     "A.RecommendingBooster",
     "A.MaintainAntibody",
     "A.NoSeriousSideEffects"]

D = ["B.RiskWithoutBooster",
     "B.SevereCompWithoutBooster",
     "B.SpreadFamilyWithoutBooster",
     "B.TransmitPatientsWithoutBooster",
     "B.SkepticalBooster",
     "B.BoosterSafe",
     "B.BoosterMoreSideEffects",
     "B.PreferNaturalImmunity",
     "B.EliminateStigma",
     "B.PublicRiskWithoutBooster"]

E = ["C.BoosterNotNeeded",
     "C.BoosterHarm",
     "C.EvidenceInsufficient",
     "C.TrustSocialMedia",
     "C.SideEffectsNoImpact"]

In [24]:
# get the mean of all the A, B, C, D and E columns

ABCDE_columns = A + B + C + D + E

# 1) Make a copy so you don't mutate the original
df_work = df_normalized_before_processing.copy()

# 2) Create aggregated columns directly
df_work["A_mean"] = df_work[A].mean(axis=1)
df_work["B_mean"] = df_work[B].mean(axis=1)
df_work["C_mean"] = df_work[C].mean(axis=1)
df_work["D_mean"] = df_work[D].mean(axis=1)
df_work["E_mean"] = df_work[E].mean(axis=1)

# 3) Save the target, drop raw ABCDE items + target, then add target back
y = df_work["AgreeSubsequentBooster"]  # keep it aside

df_normalized = df_work.drop(columns=ABCDE_columns + ["AgreeSubsequentBooster"], errors="ignore")
df_normalized["AgreeSubsequentBooster"] = y

In [25]:
df_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,A_mean,B_mean,C_mean,D_mean,E_mean,AgreeSubsequentBooster
0,0.912281,1,2,1,0,1,1,1,0.742857,0,...,0,0,0,0,1.0,2.000000,1.000000,1.8,2.6,1
1,0.614035,0,4,2,0,1,1,1,0.285714,0,...,0,0,0,0,0.0,1.666667,0.000000,1.2,4.0,1
2,1.000000,1,2,2,0,0,0,0,0.942857,1,...,0,0,0,0,1.6,1.916667,1.142857,1.8,2.0,0
3,0.824561,1,2,1,0,1,1,1,0.628571,0,...,0,0,0,0,2.0,2.166667,2.142857,2.0,2.2,0
4,0.929825,1,2,2,0,1,1,1,0.742857,0,...,0,0,0,0,0.4,1.500000,0.000000,1.4,2.6,0

In [26]:
# do the same for not normalized

# 1) Make a copy so you don't mutate the original
df_work_ii = df_not_normalized_before_processing.copy()

# 2) Create aggregated columns directly
df_work_ii["A_mean"] = df_work_ii[A].mean(axis=1)
df_work_ii["B_mean"] = df_work_ii[B].mean(axis=1)
df_work_ii["C_mean"] = df_work_ii[C].mean(axis=1)
df_work_ii["D_mean"] = df_work_ii[D].mean(axis=1)
df_work_ii["E_mean"] = df_work_ii[E].mean(axis=1)

# 3) Save the target, drop raw ABCDE items + target, then add target back
y = df_work_ii["AgreeSubsequentBooster"]  # keep it aside

df_not_normalized = df_work_ii.drop(columns=ABCDE_columns + ["AgreeSubsequentBooster"], errors="ignore")
df_not_normalized["AgreeSubsequentBooster"] = y

In [27]:
df_not_normalized.head(5)

,Age,Gender,Education,Income,Pregnant,PatientContact,Occupation,CovidPatientCare,EmploymentYears,PreExistingCondition,...,Location_Pulau Pinang,Location_Sabah,Location_Selangor,Location_Terengganu,A_mean,B_mean,C_mean,D_mean,E_mean,AgreeSubsequentBooster
0,52,1,2,1,0,1,1,1,26.0,0,...,0,0,0,0,1.0,2.000000,1.000000,1.8,2.6,1
1,35,0,4,2,0,1,1,1,10.0,0,...,0,0,0,0,0.0,1.666667,0.000000,1.2,4.0,1
2,57,1,2,2,0,0,0,0,33.0,1,...,0,0,0,0,1.6,1.916667,1.142857,1.8,2.0,0
3,47,1,2,1,0,1,1,1,22.0,0,...,0,0,0,0,2.0,2.166667,2.142857,2.0,2.2,0
4,53,1,2,2,0,1,1,1,26.0,0,...,0,0,0,0,0.4,1.500000,0.000000,1.4,2.6,0

In [28]:
# import to csv

df_normalized.to_csv('booster_normalized.csv', index=False)

In [29]:
# import to csv

df_not_normalized.to_csv('booster_not_normalized.csv', index=False)